Internal Server Error: /
Traceback (most recent call last):
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'pages/reset-senha.html' not found. 'pages/reset-senha.html' is not a valid view function or pattern name.
Internal Server Error: /
Traceback (most recent call last):
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'pages/reset-senha.html' not found. 'pages/reset-senha.html' is not a valid view function or pattern name.
"GET / HTTP/1.1" 500 115709
"GET / HTTP/1.1" 500 115709
Internal Server Error: /
Traceback (most recent call last):
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'pages/reset-senha.html' not found. 'pages/reset-senha.html' is not a valid view function or pattern name.
Internal Server Error: /
Traceback (most recent call last):
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'pages/reset-senha.html' not found. 'pages/reset-senha.html' is not a valid view function or pattern name.
"GET / HTTP/1.1" 500 115513
"GET / HTTP/1.1" 500 115513
Internal Server Error: /listagem-clientes/
Traceback (most recent call last):
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/views/generic/list.py", line 174, in get
    context = self.get_context_data()
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/cadastros/views.py", line 63, in get_context_data
    planos = Plano.objectsall()
AttributeError: type object 'Plano' has no attribute 'objectsall'
Internal Server Error: /listagem-clientes/
Traceback (most recent call last):
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/views/generic/list.py", line 174, in get
    context = self.get_context_data()
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/cadastros/views.py", line 63, in get_context_data
    planos = Plano.objectsall()
AttributeError: type object 'Plano' has no attribute 'objectsall'
"GET /listagem-clientes/ HTTP/1.1" 500 86292
"GET /listagem-clientes/ HTTP/1.1" 500 86292
Internal Server Error: /listagem-clientes/
Traceback (most recent call last):
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 839, in do_for
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'for' statements should use the format 'for x in y': for x in range(1, 32)
Internal Server Error: /listagem-clientes/
Traceback (most recent call last):
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 839, in do_for
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'for' statements should use the format 'for x in y': for x in range(1, 32)
"GET /listagem-clientes/ HTTP/1.1" 500 181092
"GET /listagem-clientes/ HTTP/1.1" 500 181092
Internal Server Error: /listagem-clientes/
Traceback (most recent call last):
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 193, in render
    values = list(values)
TypeError: 'int' object is not iterable
Internal Server Error: /listagem-clientes/
Traceback (most recent call last):
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 193, in render
    values = list(values)
TypeError: 'int' object is not iterable
"GET /listagem-clientes/ HTTP/1.1" 500 137154
"GET /listagem-clientes/ HTTP/1.1" 500 137154
Internal Server Error: /listagem-clientes/
Traceback (most recent call last):
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 193, in render
    values = list(values)
TypeError: 'int' object is not iterable
Internal Server Error: /listagem-clientes/
Traceback (most recent call last):
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 193, in render
    values = list(values)
TypeError: 'int' object is not iterable
"GET /listagem-clientes/ HTTP/1.1" 500 137154
"GET /listagem-clientes/ HTTP/1.1" 500 137154
Internal Server Error: /listagem-clientes/
Traceback (most recent call last):
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 839, in do_for
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'for' statements should use the format 'for x in y': for x in range(1, 32)
Internal Server Error: /listagem-clientes/
Traceback (most recent call last):
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 839, in do_for
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'for' statements should use the format 'for x in y': for x in range(1, 32)
"GET /listagem-clientes/ HTTP/1.1" 500 181092
"GET /listagem-clientes/ HTTP/1.1" 500 181092
Internal Server Error: /listagem-clientes/
Traceback (most recent call last):
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 852, in do_for
    sequence = parser.compile_filter(bits[in_index + 1])
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '(1,32)' from 'range(1,32)'
Internal Server Error: /listagem-clientes/
Traceback (most recent call last):
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 852, in do_for
    sequence = parser.compile_filter(bits[in_index + 1])
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '(1,32)' from 'range(1,32)'
"GET /listagem-clientes/ HTTP/1.1" 500 203230
"GET /listagem-clientes/ HTTP/1.1" 500 203230
Internal Server Error: /listagem-clientes/
Traceback (most recent call last):
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 852, in do_for
    sequence = parser.compile_filter(bits[in_index + 1])
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '(1,32)' from 'range(1,32)'
Internal Server Error: /listagem-clientes/
Traceback (most recent call last):
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 852, in do_for
    sequence = parser.compile_filter(bits[in_index + 1])
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '(1,32)' from 'range(1,32)'
"GET /listagem-clientes/ HTTP/1.1" 500 203230
"GET /listagem-clientes/ HTTP/1.1" 500 203230
Internal Server Error: /listagem-clientes/
Traceback (most recent call last):
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 852, in do_for
    sequence = parser.compile_filter(bits[in_index + 1])
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '(1,32)' from 'range(1,32)'
Internal Server Error: /listagem-clientes/
Traceback (most recent call last):
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 852, in do_for
    sequence = parser.compile_filter(bits[in_index + 1])
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "/mnt/c/Users/jreii/Desktop/IPTVGestão/.venv/lib/python3.10/site-packages/django/template/base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '(1,32)' from 'range(1,32)'
"GET /listagem-clientes/ HTTP/1.1" 500 203230
"GET /listagem-clientes/ HTTP/1.1" 500 203230
